services:
  dz_autotest:
    image: dz_autotest
    container_name: test_container
    volumes:
      - "D:\\Dev\\Auto_Test_DZ\\allure_reports:/app/report"
    entrypoint: "/app/entrypoint.sh"
    environment:
    - TEST_URL=https://clm.doczilla.pro/dev